general.live_config_reload = true

[font]
normal = { family = "HackGen Console NF", style = "Regular" }
bold = { family = "HackGen Console NF", style = "Bold"}
italic = { family = "HackGen Console NF", style = "Italic"}
bold_italic = { family = "HackGen Console NF", style = "Bold Italic"}
size = 16.0
offset = {x = 1, y = 2}

[window]
opacity = 0.85
decorations = "none"

[terminal]
shell = { program = "/bin/zsh", args = ["-l",] }


